config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  
  root 'finder#index'

  get 'alphabetized' => 'finder#alphabetized', as: 'alphabetized'
  get 'missing_email' => 'finder#missing_email', as: 'missing_email'
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/customer.rb
class Customer < ActiveRecord::Base
	belongs_to :province
	validates :full_name, presence: true
end

app/models/province.rb
class Province < ActiveRecord::Base
	has_many :customers

	validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/finder_controller.rb
class FinderController < ApplicationController
	def index
		@page_title = 'All Customers'
		@customers = Customer.all
	end

	def alphabetized
		@page_title = 'Alphabetized Customers'
		@customers = Customer.order(:full_name)
		render :index
	end

	def missing_email
		@page_title = 'Customers Missing Email Addresses'
		@customers = Customer.where(email_address: '')
		render :index
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/finder_helper.rb
module FinderHelper
end

app/views/customers/_customer.html.erb
<h2><%= customer.full_name %></h2>
<p><strong>Phone Number:</strong> <%= customer.phone_number %></p>
<p><strong>Province:</strong>
<% if customer.province.present? %>
	<%= customer.province.name %></p>
<% else %>
	None
<% end %>

app/views/finder/index.html.erb
<h1><%= @page_title %></h1>

<%= render @customers %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CookieCrm</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<header>
	<nav>
		<ul>
			<li><%= link_to 'Home', root_path %></li>
			<li><%= link_to 'Alphabetized', alphabetized_path %></li>
			<li><%= link_to 'Missing Email', missing_email_path %></li>
		</ul>
	</nav>
</header>
<%= yield %>

</body>
</html>